/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nchalkova_fibonacci_FibonacciFacade */

#ifndef _Included_ru_nchalkova_fibonacci_FibonacciFacade
#define _Included_ru_nchalkova_fibonacci_FibonacciFacade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nchalkova_fibonacci_FibonacciFacade
 * Method:    getNativeFib
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ru_nchalkova_fibonacci_FibonacciFacade_getNativeFib
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
